import React from 'react';
import CrudModule from '@/modules/CrudModule/CrudModule';
import TaxForm from '@/forms/TaxForm';
import { fields } from './config';
import useLanguage from '@/locale/useLanguage';

export default function Taxes() {
  const translate = useLanguage();

  // 'tax' needs to match the entity name generated by your backend utils
  const entity = 'tax';

  const searchConfig = {
    displayLabels: ['taxName'],
    searchFields: 'taxName',
  };

  const deleteModalLabels = ['taxName'];

  const Labels = {
    PANEL_TITLE: translate('taxes'),
    DATATABLE_TITLE: translate('taxes_list'),
    ADD_NEW_ENTITY: translate('add_new_tax'),
    ENTITY_NAME: translate('tax'),
  };

  const configPage = {
    entity,
    ...Labels,
  };

  const config = {
    ...configPage,
    fields,
    searchConfig,
    deleteModalLabels,
  };

  return (
    <CrudModule
      createForm={<TaxForm />}
      updateForm={<TaxForm isUpdateForm={true} />}
      config={config}
    />
  );
}
